US[01] - Manter Processos
fga-eps-mds/2022-1-CAPJu-Interface pull request #19
Opened 2022-09-06 15:58 UTC by luclopesr

## Issue [#68](https://github.com/fga-eps-mds/2022-1-CAPJu-Doc/issues/68)

## Descrição

Foram desenvolvidas as seguintes melhorias:
- Mostrar se a etapa está vencida ou não, por meio das cores verde ou vermelho, na lista de processos;
- Adicionar o número da etapa na lista de processos, tanto na Etapa Atual quanto na Última Etapa;
- Aumento da cobertura de testes.
## Screenshots (se apropriado):

## Tipos de Mudanças

- [ ] Bug fix (alteração ininterrupta que corrige um problema)
- [x] Nova feature (mudança ininterrupta que adiciona funcionalidade)
- [ ] Breaking change (correção ou recurso que faria com que a funcionalidade existente não funcionasse como esperado)
- [ ] Documentação (adição ou remoção de algum artefato)

## Checklist:

- [x] Meu código segue os padrões de estilo deste projeto.
- [ ] Minha alteração requer uma alteração na documentação.
- [ ] Atualizei a documentação de acordo.

2022-09-06 18:01 UTC, FranciscoHeronildo requested changes
Foi identificado erros no eslint em seu arquivo de setupTest, por gentileza solucione o problema para poder ter o Pull Request Aprovado

2022-09-07 01:50 UTC, luclopesr commented
> Foi identificado erros no eslint em seu arquivo de setupTest, por gentileza solucione o problema para poder ter o Pull Request Aprovado

Requisição concluída!

2022-09-07 03:58 UTC, FranciscoHeronildo commented on src/components/IsLate/index.js
> +    return true;
Os retornos booleanos podem ser simplificados

2022-09-07 04:02 UTC, luclopesr commented on src/components/IsLate/index.js
> +    return true;
Corrigido!

2022-09-07 09:05 UTC, FranciscoHeronildo approved these changes
Obrigado pela sua contribuição

2022-09-07 09:06 UTC, merged